name: add_products_script
description: Script to add sample products to Firestore
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3

